services:
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'sail'
      MYSQL_PASSWORD: 'password'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}" ]
      retries: 3
      timeout: 5s

volumes:
  mysql-data:
